version: '3'
services:
  backend:
    build: ./scala-project
    ports:
      - "9000:9000"
    volumes: 
      - ./scala-project/data:/:/home/backend/data
    command: sbt run
  frontend:
    stdin_open: true
    build: ./client
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    command: npm start