version: '3'
services:
  backend:
    build: ./scala-project
    ports:
      - "9000:9000"
    volumes: 
      - path/to/database:/home/backend/ebiznes.db
      - path/to/silhouette.conf:/home/backend/conf/silhouette.conf
    command: sbt run
  frontend:
    stdin_open: true
    build: ./client
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    command: npm start