const CART_SET_ITEMS = 'CART_SET_ITEMS';
const CART_ADD = 'CART_ADD';
const CART_REMOVE = 'CART_REMOVE';
const CART_CLEAR = 'CART_CLEAR';

export default {
    CART_SET_ITEMS,
    CART_ADD,
    CART_REMOVE,
    CART_CLEAR
};